### PR TITLE
Added new external example object diagram modeler to the README.

### PR DESCRIPTION
**Pull request by timKraeuter**
I implemented an object diagram viewer and editor based on diagram-js.
I would like it to be included in the external examples.

### CODE REVIEW

**Comment by nikku** [comment]
Interesting contribution. 

Before we merge it, could you elaborate what this does? Does `Object Diagram` refer to UML?

**Comment by timKraeuter** [comment]
Yes, `Object Diagram` refers to UML object diagrams. One can notate object diagrams using the modeler, but the exported XML files can only be imported in the modeler itself. There is, to my knowledge, currently no defined exchange format for object diagrams in the UML specification.

I was mainly interested in an object diagram viewer in the web, which allows user interaction for my [Visual Debugger Plugin](https://plugins.jetbrains.com/plugin/16851-visual-debugger). Having an editable modeler was a welcome side project.

**Comment by timKraeuter** [comment]
What do you think @nikku ?

**Review by barmac — APPROVED** [review]
Let's merge this.

**Pull request merged**
