### PR TITLE
feat(resize): resize horizontally and vertically

### LINKED ISSUE #117: Allow shape resizing by dragging edges
It should be possible to resize a shape in one dimension (vertically or horizontally) by dragging the edge.

On hover over an edge, a horizontal/vertical resize cursor should be shown (even if the element is not selected).

### PR DESCRIPTION
**Pull request by philippfromme**
Closes #117

### CODE REVIEW

**Comment by philippfromme** [comment]
@nikku Following up our discussion about how resizing works in other tools:

#### Adobe Illustrator

Exactly the same.

illustrator

#### Google Drawings/Slides

Exactly the same.

google-slides

**Comment by nikku** [comment]
Thanks for investigating this @philippfromme :rocket:.

**Comment by nikku** [comment]
Experimenting with the visual representation of the resize handles I have a proposal: 

* As we have the "Shape has a visual outline" pattern, let's center the resize handles around that outline. 
* Slightly reduce the visual presence of the handles (the interaction rectangle stays intact)

__Proposed Change__

image

__Original__

image

**Comment by philippfromme** [comment]
👍

**Comment by philippfromme** [comment]
Awesome! 👏

**Pull request merged**
