### PR TITLE
Remove orange color from preview

### PR DESCRIPTION
**Pull request by barmac**
> ...because black is new orange.

This PR removes orange color from previews.

### CODE REVIEW

**Comment by nikku** [comment]
Let us consider this change not in isolation but together with all the other connection preview related improvements we have in mind.

Could you record before/after captures so we have a solid base for comparison of the different mechanism?

**Comment by barmac** [comment]
Sure, I will do this.

**Comment by barmac** [comment]
Element creation:

new-element-old 
new-element


Connections:

create-old 
create

**Comment by barmac** [comment]
It's not gonna be merged, at least not yet.

**Pull request closed without merging**
