### PR TITLE
Show Resize Handles on Hover

### PR DESCRIPTION
**Pull request by philippfromme**
* shows resize handles on selection _and_ hover which is consistent with outline behavior
* increases size of handles which is consistent with size of bendpoint draggers

zStGQ7w7Sh

### CODE REVIEW

**Comment by nikku** [comment]
Can we separate the two concerns? I'm happy with the resize on hover, however I'd like us to try a number of variations for the resize handles. I personally find these handles are too big / gimmicky, especially if things start to blink now on hover. 

Before settling on an improvement in that area I'd like us to explore other options mentioned last Friday, such as increasing the opacity of the handles to make them easier recognizable.

**Comment by andreasgeier** [comment]
I believe the increased size is better recognizable than before. I quickly checked some other tools, they use similar sizes:

Miro
Screen Shot 2021-04-22 at 08 20 20

Sketch
Screen Shot 2021-04-22 at 08 20 54

Figma
Screen Shot 2021-04-22 at 08 21 53

**Comment by andreasgeier** [comment]
What is confusing - but this might be another topic - is that the resize can cause a hover state on other elements. It can be seen in the screen record above.

**Comment by nikku** [comment]
@andreasgeier out of curiosity, could you share how these tools deal with rounded corner elements?

**Review by nikku — COMMENTED** [review]
I'll look into a small variation of the handle (including color change).

**Comment by andreasgeier** [comment]
> @andreasgeier out of curiosity, could you share how these tools deal with rounded corner elements?

Screen Shot 2021-04-22 at 11 21 59
Screen Shot 2021-04-22 at 11 22 18
Screen Shot 2021-04-22 at 11 22 54

**Review by nikku — APPROVED** [review]
Let's do this!

**Comment by nikku** [comment]
Unfortunately I ran into a bug with the resize handles implementation. Essentially the editor blows up every time you activate direct editing after creating a new element:

capture T6jtsY_optimized

My suggestion would be to revert the changes for the moment and see when / how we can address this one. What do you think @philippfromme?

**Comment by philippfromme** [comment]
We agreed to revert the changes for now and tackle this later.

**Comment by nikku** [comment]
Reverted via https://github.com/bpmn-io/diagram-js/pull/547.

**Pull request merged**
