### PR TITLE
fix: limit size of context pad entry image

### PR DESCRIPTION
**Pull request by barmac**
This is to make sure that I can provide SVGs without worrying about the icon size.

### CODE REVIEW

**Review by nikku — CHANGES_REQUESTED** [review]
Could you add an example to the existing context pad specs to verify this (visually)?

**Comment by barmac** [comment]
I tried to but then it occurred that none of the images in the current example are displayed correctly :D Let me push those changes.

**Comment by barmac** [comment]
Hmm it seems to work. I will add a proper test.

**Comment by barmac** [comment]
OK I've added a test case. This will be required for the alignment icons.

**Comment by barmac** [comment]
Learning: image loads asynchronously so we need to wait before we compare size.

**Review by nikku — COMMENTED** [review]
Works for me. 

An alternative is to enforce the correct size directly, did you consider it?

**Comment by barmac** [comment]
> Works for me.
> 
> An alternative is to enforce the correct size directly, did you consider it?

Via `style`? I have not. In what way could it improve the solution?

**Comment by nikku** [comment]
> In what way could it improve the solution?

It would enforce a consistent sizing, not just max sizing. Generally I'd go an extra step to ensure users do not shoot themselves in the foot.

**Review by nikku — APPROVED** [review]

**Pull request merged**
