### PR TITLE
Add ability to render connections with round corners

### PR DESCRIPTION
**Pull request by nikku**
Foundation for toolkits to build on top of this:

image

### CODE REVIEW

**Comment by marstamm** [comment]
Very cool! I tried it out using the bpmn-js branch and found one weird behavior when merging bendpoints:

Recording 2023-02-02 at 13 27 08

**Comment by nikku** [comment]
Thanks for the review. Will verify https://github.com/bpmn-io/diagram-js/pull/747#issuecomment-1413663510 and come back with this later.

**Comment by nikku** [comment]
I'd ask you to check this out again. Works on my machine, but I had to update https://github.com/bpmn-io/bpmn-js/pull/1828 to the latest commit on this branch.

capture iYiqN3_optimized

**Review by marstamm — APPROVED** [review]
I linked it locally and everything works 🚀 

npm used an outdated commit hash from the package-lock on the initial install

**Pull request merged**
