### PR TITLE
[WIP] Feature/es6

### LINKED ISSUE #482: Migrate code base to ES6
As of version 1.0.0 this library exposes ES modules.
We use bundler such as Webpack or Rollup to bundle library

Why are we still using es4 syntax with prototypes?
All modern browsers support es5 at least.

Even if we want support old ones in any case we use webpack for bundling.

For example, we can change this "class":
```js
import {
  create
} from '../model';

import { assign } from 'min-dash';

/**
 * A factory for diagram-js shapes
 */
export default function ElementFactory() {
  this._uid = 12;
}


ElementFactory.prototype.createRoot = function(attrs) {
  return this.create('root', attrs);
};

ElementFactory.prototype.createLabel = function(attrs) {
  return this.create('label', attrs);
};

ElementFactory.prototype.createShape = function(attrs) {
  return this.create('shape', attrs);
};

ElementFactory.prototype.createConnection = function(attrs) {
  return this.create('connection', attrs);
};

/**
 * Create a model element with the given type and
 * a number of pre-set attributes.
 *
 * @param  {string} type
 * @param  {Object} attrs
 * @return {djs.model.Base} the newly created model instance
 */
ElementFactory.prototype.create = function(type, attrs) {

  attrs = assign({}, attrs || {});

  if (!attrs.id) {
    attrs.id = type + '_' + (this._uid++);
  }

  return create(type, attrs);
};
```
to the modern one:
```js
import {
  create
} from '../model';

import { assign } from 'min-dash';

/**
 * A factory for diagram-js shapes
 */
export default class ElementFactory {
  constructor() {
    this._uid = 12;
  }

  createRoot(attrs) {
    return this.create('root', attrs);
  }

  createLabel(attrs) {
    return this.create('label', attrs);
  }

  createShape(attrs) {
    return this.create('shape', attrs);
  }

  createConnection(attrs) {
    return this.create('connection', attrs);
  }

  /**
   * Create a model element with the given type and
   * a number of pre-set attributes.
   *
   * @param  {string} type
   * @param  {Object} attrs
   * @return {djs.model.Base} the newly created model instance
   */
  create(type, attrs) {

    attrs = assign({}, attrs || {});

    if (!attrs.id) {
      attrs.id = type + '_' + (this._uid++);
    }

    return create(type, attrs);
  }
}
```

I can do the most migration by myself, but will it be ever merged?

### PR DESCRIPTION
**Pull request by FrankiePo**
Converts es4 syntax to es6 using [lebab](https://github.com/lebab/lebab)
Closes #482

### CODE REVIEW

**Comment by pinussilvestrus** [comment]
Thanks for the PR! We will discuss internally how to proceed with the changes you suggested.

In the meantime, can you adapt your pull request to fit our [contribution guidelines](https://github.com/bpmn-io/diagram-js/blob/develop/.github/CONTRIBUTING.md#creating-a-pull-request)? At least one test is failing and the commit messages are not in the structure we want to have them.

**Comment by FrankiePo** [comment]
@philippfromme It's only the example of work I was suggesting in #482

The test failing in ChromeHeadless even in develop branch see #485
I will format my commit/pr messages as soon as I'll done the rest of the work.

The main question is am i doing right and do the team has any other wishes?

**Comment by nikku** [comment]
Could you provide me with the details how you converted the files? I gave lebab a try but unfortunately it fails to migrate most of our classes to ES6 class syntax:

```
diagram-js/lib/node_modules/lebab/lib/utils/multiReplaceStatement.js:66
      throw "Unsupported node type '".concat(node.type, "' in multiReplaceStatement()");
      ^
Unsupported node type 'ExportDefaultDeclaration' in multiReplaceStatement()
(Use `node --trace-uncaught ...` to show where the exception was thrown)
```

**Comment by FrankiePo** [comment]
@nikku ye, it doesn't support `export default`

I did this steps:
1. Remove export default
2. Use `lebab` through vscode plugin using hotkey
3. Add export default
4. Run tests
5. Repeat for every file

Also `lebab` couldn't convert some classes correctly and tests began failing.

**Comment by nikku** [comment]
Closing this due to https://github.com/bpmn-io/diagram-js/issues/482#issuecomment-705557444.

**Comment by nikku** [comment]
Ended up creating a supporting script to workaround the lebab issue: https://gist.github.com/nikku/6103cd0cc7a5b081b35b5cdbc3d13946

Still, a lot of manual labor remains.

**Pull request closed without merging**
