### PR TITLE
Align colors with Camunda Modeler

### LINKED ISSUE #476: Color alignment with Camunda Modeler
__What should we do?__

Implement the colors described in https://github.com/camunda/camunda-modeler/issues/1844

__Why should we do it?__

Rebranding & product alignment.

### PR DESCRIPTION
**Pull request by oguzeroglu**
Closes #476

### CODE REVIEW

**Comment by oguzeroglu** [comment]
WIP because Andi needs to review this too. Code is ready for a review otherwise.

**Comment by oguzeroglu** [comment]
I set the definitions to .djs-container scope rather than root scope.

**Comment by oguzeroglu** [comment]
I modified the context pad hover color that Andi mentionned in his review. The rest is compatible with the v1 version of the designs. So we can merge this IMO.

**Comment by philippfromme** [comment]
There's one failing test case. Let me fix that.

**Pull request merged**
