### PR TITLE
fix console error when pressing align elements with no selection

### PR DESCRIPTION
**Pull request by quintanamartin**
This PR has the purpose to fix the console error when user presses align with no selection done, corresponding to the issue #533. I only added this:
function getMiddleOrTop(first, last) {
        if (first === undefined || last === undefined) {
            return;
        } else {
            return Math.round((first[axis] + last[axis] + last[dimension]) / 2);
        }
    } 
Thanks in advance!

### CODE REVIEW

**Comment by pinussilvestrus** [comment]
Thanks first for your time to work on this!

However, it will be tough to review this one until it's not following our [Definition of Done](https://github.com/bpmn-io/diagram-js/blob/develop/.github/PULL_REQUEST_TEMPLATE.md). This means in particular
* Please be descriptive of what changes you are proposing and why are they necessary (cf. https://github.com/bpmn-io/diagram-js/issues/533#issuecomment-773840349)
* Please format your code. It should be clear which changes this PR introduces.
* Fix your commit message to [fit our guidelines](https://www.conventionalcommits.org/)
* Add a test case, which describes the problem and verifies it got fixed
* Make sure CI is running green

Thank you ❤️

**Comment by quintanamartin** [comment]
Ok, I'm really sorry for not being that clear and for the indenting problem. This is my first time doing this! I will be working on this the weekend so I could be clear about the problem and the solution. Thanks!

**Comment by pinussilvestrus** [comment]
We really appreciate the time you spend with our toolkit and your willingness to improve it! That's the power of open source ❤️ 

It's no big deal that you didn't fulfill the requirements on the first try. This can happen. I can remember I did similar mistakes when I started contributing to open source projects 🙂 

There is also no need to rush. If you have questions about getting the PR prepared, we're always here to help. 👋🏻

**Comment by nikku** [comment]
@quintanamartin We do not know what the problem is you'd like to solve (https://github.com/bpmn-io/diagram-js/issues/533#issuecomment-776955204), thus we cannot evaluate if what you propose as a solution makes sense or not.

Because of that I'm closing your PR.

**Comment by nikku** [comment]
Happy to fix any bug / accept bug fixing contributions if we understand what is broken.

**Pull request closed without merging**
