### PR TITLE
Make Canvas Selectable

### PR DESCRIPTION
**Pull request by philippfromme**
Makes the canvas selectable by adding a `tabindex` attribute.

### Camunda Modeler

Camunda_Modeler_28n1swge1e

### CODE REVIEW

**Comment by nikku** [comment]
Follow up improvement: Hook up keyboard bindings with canvas only, and trigger bindings only if canvas has browser focus.

Proposing this as `spring cleaning`.

**Comment by nikku** [comment]
What keeps us from progressing with this one?

**Comment by philippfromme** [comment]
Last week it wasn't clear if we're going to add more things. But we can go ahead and merge this now.

**Review by nikku — APPROVED** [review]
Added a [test case](https://github.com/bpmn-io/diagram-js/pull/659/commits/6f7234f5379defa47e62ee459895b970bf05ddd6)

**Pull request merged**
