### PR TITLE
fix(plane): render content behind resize handles

### PR DESCRIPTION
**Pull request by marstamm**
Related to https://github.com/bpmn-io/bpmn-js/issues/1520

### CODE REVIEW

**Review by nikku — APPROVED** [review]

**Comment by nikku** [comment]
Test currently fails on PhantomJS:

```
PhantomJS 2.1.1 (Linux x86_64) features/resize - Resize handles should sit infront of content planes FAILED
	Can't call method on undefined
	
	invoke	
```

**Comment by marstamm** [comment]
PhantomJS does not like slice

**Comment by nikku** [comment]
You can also trial PhantomJS via `TEST_BROWSERS=PhantomJS npm test`.

**Review by nikku — COMMENTED** [review]
I've moved the test to the CanvasSpec, where it belongs from my point of view: https://github.com/bpmn-io/diagram-js/pull/584/commits/6973536e4a562aed7afaa05e2e83de3e2f348c77

It is a core infrastructure (plane creation) that is broken, nothing resize related.

**Comment by marstamm** [comment]
Makes sense, thank you for looking into this

**Review by nikku — APPROVED** [review]

**Pull request merged**
