### PR TITLE
Handle keyboard input without search active

### LINKED ISSUE #701: Arrow keys don't work in popup menu
__Describe the Bug__

Arrow keys don't work in popup menu when search is turned off

__Steps to Reproduce__

https://user-images.githubusercontent.com/28307541/203007560-46020f63-1b4d-47fe-9dd0-7dae0cdc21ef.mov

1. open popup menu for sub process
2. use arrow up/down
3. see that element moves instead of navigating the menu

__Expected Behavior__

The arrow keys should result in menu navigation

__Environment__

Please complete the following information:

 - Library version: 11.0.0

### PR DESCRIPTION
**Pull request by nikku**
Depends on https://github.com/bpmn-io/diagram-js/pull/706, https://github.com/bpmn-io/diagram-js/pull/709, https://github.com/bpmn-io/diagram-js/pull/708.

----
 
Closes #701

### CODE REVIEW

**Comment by nikku** [comment]
@smbea Without additional context could you user test the latest changes on this branch. Does it feel intuitive for you?

**Comment by nikku** [comment]
> https://github.com/bpmn-io/diagram-js/pull/710#issuecomment-1324998345

Thanks for the feedback. We could ensure that "automatic selection" only happens if there is actual keyboard filtering happening. Why we have it in the first place: To support a streamlined keyboard selection flow.

**Comment by nikku** [comment]
Getting rid of the initial keyboard focus feels odd, too. For users to understand that they can navigate using the keyboard they need an initial visual indication.

Let's leave it like this; I'll try to see if I can ramp up the test coverage.

----

For comparison menu:

image

And similar menu in Camunda Desktop Modeler:

capture bwx5rz_optimized

**Review by barmac — APPROVED** [review]
It works great. I wouldn't change anything interaction-wise.

**Comment by nikku** [comment]
Following up on the proposed improvements here: https://github.com/bpmn-io/diagram-js/pull/711.

This branch can be reviewed independently.

**Pull request merged**
