### PR TITLE
feat(popup-menu): support multiple classnames on popup-menu entries

### PR DESCRIPTION
**Pull request by felixlinker**
### Proposed Changes

* A popup-menu entry can now accept multiple classes as `className` each of them delimited by a space, e. g. `className: 'class1 class2'`

### CODE REVIEW

**Comment by nikku** [comment]
What is the use-case for this?

**Comment by felixlinker** [comment]
I'm using the modeler in an "embedded" scenario. In my case, it is used in Wordpress. I'd like to add a popup-menu entry that has one of the pre-existing icons that come shipped with wordpress displayed. To use one of those, I need to add two classes: `dashicons-before dashicons-ICON_NAME`.

However, this scenario applies to many frameworks, such as bootstrap. There you also need to add two classes to a `<span>` in order for it to display a glyphicon. ([Click here for an example](https://getbootstrap.com/docs/3.3/components/))

**Comment by nikku** [comment]
Sounds legitimate!

Could you add test coverage that ensures your contribution works? [`PopupMenuSpec`](https://github.com/bpmn-io/diagram-js/blob/master/test/spec/features/popup-menu/PopupMenuSpec.js) is the right place to do so.

**Comment by felixlinker** [comment]
Done ✔️

**Comment by nikku** [comment]
Thanks.

**Pull request merged**
