### PR TITLE
Adding charCode compare(multilanguage support)

### PR DESCRIPTION
**Pull request by Quieska**
Added charCode compare(multilanguage support)
The proplem it fixed is hotkeys (ctrl+z, ctrl+c ... etc.) not working in other locales.
Now hotkeys working in all languales (Russian, Serbian... etc.) :)

### CODE REVIEW

**Comment by nikku** [comment]
Thanks for your PR!

Could you elaborate on what you do and why?

If you contribute fixes, please also consider adding accompanying test cases.

**Comment by Quieska** [comment]
keys.indexOf(event.key) > -1
keys is an array [z, Z].
event.key in English locale is "z" for example, but in my another locale it is "я"
It's not working with finding String. 
It can be fixing by taking event.keyCode, transform to String and search it in keys array

**Comment by Quieska** [comment]
> Thanks for your PR!
> 
> Could you elaborate on what you do and why?
> 
> If you contribute fixes, please also consider adding accompanying test cases.

Hello! Thanks for your reply!
I made some test cases. You can remove comparing by keyCode and see that new test cases failing :)

**Comment by nikku** [comment]
To better understand your case you'd still press `CTRL + я` on your keyboard as a UNDO shortcut?

**Comment by Quieska** [comment]
> To better understand your case you'd still press `CTRL + я` on your keyboard as a UNDO shortcut?

Yes, all shortcuts works like earlier, but not only in english locale

**Comment by nikku** [comment]
This is an interesting detail, indeed.

Looking at my german keyboard (where `Z` and `Y` are swapped): Given your solution, pressing the English keyboard shortcut would yield `CTRL + Z` even though it says `CTRL + Y` and I'd expect it to REDO.

Guess we'll need to investigate this issue a little further.

**Comment by Quieska** [comment]
> This is an interesting detail, indeed.
> 
> Looking at my german keyboard (where `Z` and `Y` are swapped): Given your solution, pressing the English keyboard shortcut would yield `CTRL + Z` even though it says `CTRL + Y` and I'd expect it to REDO.
> 
> Guess we'll need to investigate this issue a little further.

So look on it not like CTRL+Z(on english) or CTRL+Y(on german) or CTRL+Я(on russian)
It CTRL+*KeyCode = 90* for UNDO for all locales. That what i did.

**Comment by philippfromme** [comment]
Actually, undoing on a German keyboard is CTRL + Z, the physical key is just somewhere else on the keyboard.

**Comment by philippfromme** [comment]
So the issue is that `key` is referring to the character that's generated whereas both `keyCode` and the more recent `key` refer to the physical key on the keyboard. Since we're only using `key` right now the shortcuts are working on QWERTY-based Latin-script keyboard layouts but not on others. We should use both `key` and as a fallback `keyCode` to ensure the shortcuts are working properly on all keyboards.

**Comment by philippfromme** [comment]
We shouldn't use `charCode` as it's both non-standard and deprecated.

**Comment by philippfromme** [comment]
Hey @Quieska,

since I have not received a response from you I took over this PR and finished it. Thank you for bringing up this topic. In future releases, the shortcuts will work across all keyboards.

Closed via https://github.com/bpmn-io/diagram-js/pull/460.

**Comment by Quieska** [comment]
Hello @philippfromme!
Nice to hear it. I saw your PR and think it will work fine, especially you tested it on russian keyboard) Thanks for fast work! Me and my company waiting for future release.

**Pull request closed without merging**
