### PR TITLE
Do not show connect allowed markers on bendpoint move

### LINKED ISSUE #382: Moving / adding waypoint shows attach feedback
__Describe the Bug__

Updating the connection waypoints shows the  attach feedback since `v4.0.0`. This should not happen. Segment move does not show it, too.

capture qY1iZB_optimized

__Steps to Reproduce__

* Draw a connection
* Add or move bendpoint

__Expected Behavior__

* [ ] Attach feedback is not shown (similar to parallel segment move)

__Environment__

Please complete the following information:

 - Browser: All
 - OS: All
 - Library version: `v4.0.0`

### PR DESCRIPTION
**Pull request by nikku**
Closes #382

### CODE REVIEW

**Comment by philippfromme** [comment]
Is the change in the `package-lock.json` intentional?

**Comment by nikku** [comment]
Yep, that change mitigates `npm audit` warnings.

**Comment by nikku** [comment]
Please have another look :sun_behind_small_cloud:

**Comment by philippfromme** [comment]
Will do.

**Pull request merged**
