### PR TITLE
Support array of classNames when adding entries

### PR DESCRIPTION
**Pull request by narve**
feat(palette): When adding entries, allow className to be an array of strings.

### CODE REVIEW

**Comment by narve** [comment]
Sorry, technical error - updated the PR with the code that actually passed the tests :)

**Comment by nikku** [comment]
In order to merge this PR we need a test case verifying the newly added functionality.

**Comment by narve** [comment]
Can I interpret this as "you generally agree to the requirement/functionality/solution"? If so I can add a test case and update the PR. 

I also considered allowing className to contain spaces and split the string, but in general I prefer a more structured approach.

**Comment by nikku** [comment]
> Can I interpret this as "you generally agree to the requirement/functionality/solution"? If so I can add a test case and update the PR.

Yes, makes sense all together. Maybe we can go for both, space separated class list and array?

**Comment by narve** [comment]
Hm... I prefer the array-approach... then I don't have to research what "space" actually, is according to html-specs, and how to split on that in javascript :)

As long as it is possible to use an array, and this is a plausible (obviously, since I needed it) but not very common requirement, I believe that arrays should be good enough.

**Comment by nikku** [comment]
Merged with some changes via https://github.com/bpmn-io/diagram-js/commit/59438339a8ad29bac790804bc56497447b63b0b1.

Added the same functionality for the context pad, too: https://github.com/bpmn-io/diagram-js/commit/53cc1d431da2b9a112fa8329ca4eff3a45e586be

**Comment by nikku** [comment]
Thanks for your contribution.

**Comment by narve** [comment]
Superb, thanks! I was just writing a comment, asking whether I should update the PR or not, when the page updated itself  :)

**Pull request closed without merging**
