### PR TITLE
fix: repeat import isMac method

### PR DESCRIPTION
**Pull request by andyqier88**

### CODE REVIEW

**Comment by nikku** [comment]
Thanks. Great cleanup. Could you accept our CLA? We cannot merge your contribution otherwise.

**Comment by andyqier88** [comment]
> Thanks. Great cleanup. Could you accept our CLA? We cannot merge your contribution otherwise.

I have agreed to the CLA for bpmn-io/diagram-js
image

**Comment by nikku** [comment]
Please use the same email address for your fix like the one you have on GitHub. Otherwise the CLA does not count as approved.

**Comment by nikku** [comment]
You did overlook the different semantics of `import` and `export`. The `isMac` utility is both imported (and exported), hence the two declarations.  

On your PR our CI failing indicates this: https://github.com/bpmn-io/diagram-js/runs/6467668191?check_suite_focus=true.

**Comment by andyqier88** [comment]
> You did overlook the different semantics of `import` and `export`. The `isMac` utility is both imported (and exported), hence the two declarations.
> 
> On your PR our CI failing indicates this: https://github.com/bpmn-io/diagram-js/runs/6467668191?check_suite_focus=true.

Sorry for cursory PR, i will be careful next time

**Pull request closed without merging**
