### PR TITLE
chore(CHANGELOG): update with breaking change

### PR DESCRIPTION
**Pull request by barmac**
We missed the reason why it's going to be a major version. This PR adds the breaking change to the changelog.

### CODE REVIEW

**Comment by nikku** [comment]
To be honest we should probably do a dry run on upgrading DMN and CMMN to see if there exists more of such changes. Could you do that?

**Comment by nikku** [comment]
Snapping seems to be another breaking change:

image

**Comment by nikku** [comment]
In diagram-js we've introduced a large number of additional snap points secretly via https://github.com/bpmn-io/diagram-js/commit/8469f3cb270164406cbab580a93a77ba2164abcb.

We got to decide whether to undo that change (and give toolkit consumers more fine grained control) or market that as a feature.

**Comment by barmac** [comment]
@nikku No test failures in dmn-js after `diagram-js@4.0.0-beta.6` installation.

**Comment by nikku** [comment]
So it seems like the only breaking bit is the additional snap points that I propose to unbuild (cf. https://github.com/bpmn-io/bpmn-js/issues/1104). Thanks for investigating.

**Pull request merged**
