### PR TITLE
feat(popup-menu): add fuzzy search

### PR DESCRIPTION
**Pull request by philippfromme**
Related to https://github.com/camunda/camunda-modeler/issues/4122

Test via `npx @bpmn-io/sr bpmn-io/bpmn-js#fuzzy-search -l bpmn-io/diagram-js#fuzzy-search`

### CODE REVIEW

**Review by nikku — COMMENTED** [review]
Two thoughts:

* We introduce another library, let's assess the weight it adds (to a standard modeling distribution)
* We introduce fuzzy search, do we want to provide it as a feature so other parts can build on top? We have a `search` feature and I'd argue it should use the same behavior.

Alternative:

* Make search a pluggable concern, and plug-in fuzzy search outside of the core.

**Comment by philippfromme** [comment]
> * Make search a pluggable concern, and plug-in fuzzy search outside of the core.

If we were to do this, at would level would we include fuzzy search? camunda-bpmn-js?

**Comment by nikku** [comment]
@philippfromme Depends; for our use-case it would probably be camunda-bpmn-js, yes.

**Comment by philippfromme** [comment]
Since the solution is going to be fairly different, I will close this PR and open a new one.

**Pull request closed without merging**
