### PR TITLE
fix(util): properly assign helper-svg styles

### PR DESCRIPTION
**Pull request by nikku**
Related to https://github.com/bpmn-io/bpmn-js/issues/1692

### CODE REVIEW

**Comment by barmac** [comment]
I can't reproduce the original issue on Mac. @philippfromme @Skaiir one of you could probably help out here.

**Comment by nikku** [comment]
Interesting that this is not an issue on MacOS? I guess you're also using latest Chrome to test?


You should however be able to reproduce the fact that the original code (fixed) does not do what it is supposed to do.

Assigning `visibility: none` to a DOM element does nothing. This works for SVG only, sometimes.

**Comment by barmac** [comment]
> Interesting that this is not an issue on MacOS? I guess you're also using latest Chrome to test?

I checked once more on the demo site and I could reproduce the problem to some extent. It required that I scrolled while hovering the text on the bottom or the bpmn.io logo.

Scrollbars are not normally visible on Mac, but they appear when I initiate scrolling. This was possible before your changes and impossible after they were applied.

**Review by barmac — APPROVED** [review]
This fixes the issue. Each of the style properties is required for the fix to work.

**Comment by barmac** [comment]
Hmm this could have been merged to `master`.

**Comment by nikku** [comment]
:see_no_evil:

**Pull request merged**
