### PR TITLE
fix(create): only update preview if hover

### PR DESCRIPTION
**Pull request by philippfromme**
Related to camunda/camunda-modeler#1481

### CODE REVIEW

**Comment by nikku** [comment]
Trying out the solution it feels a little bit odd that the behavior on create and move differs substantially now: With create the participant gets stuck and with move, movement is still allowed.

capture 5ZuTog_optimized

Additionally, the behavior you implemented is not [what we thought was the most suitable solution](https://github.com/camunda/camunda-modeler/issues/1481#issuecomment-525184023). If the user drops the participant outside the canvas it will still be simply gone.

Given these points I'd rather not merge the solution as is.

Potential solutions to explore: 

* [actually implement our idea, allowing drop when releasing mouse outside the canvas](https://github.com/camunda/camunda-modeler/issues/1481#issuecomment-525184023)
* Indicating drop not allowed on canvas when hover is not set

**Comment by philippfromme** [comment]
Dropping outside the canvas wasn't possible anyway since https://github.com/bpmn-io/diagram-js/pull/399. We hide the preview whenever the user leaves the canvas since this would indicate that creating is not allowed outside of the canvas.

**Comment by nikku** [comment]
I guess what is missing in #399 is a visual indication:

* hiding preview
* showing drop not allowed on canvas

I'd be absolutely fine with option :three: 

* make root element hover target if no hover and display visualizations / feedback accordingly

**Comment by philippfromme** [comment]
I've added another commit; the preview is only displayed if there is a hover target. I'd argue against allowing the user to create elements while not hovering the canvas as he doesn't see what he's doing.

hover

**Comment by nikku** [comment]
This looks much better. Thanks for doing an additional round :oil_drum:

**Comment by philippfromme** [comment]
❤️

**Comment by nikku** [comment]
I've made this one a feature, as it's a little bit too much of an interaction update to release as a bug fix. 

Thanks for contributing this improvement!

**Pull request merged**
