### PR TITLE
Add to Selection When Using Lasso Tool with Shift Key

### PR DESCRIPTION
**Pull request by philippfromme**
brave_Klg6MpQEpJ

---

Related to https://github.com/bpmn-io/bpmn-js/issues/2053

### CODE REVIEW

**Comment by nikku** [comment]
Nit-pick: If I start the tool without `SHIFT` I'd expect the existing selection to go away:

capture 732iKl_optimized

Observation: We break existing `SHIFT` + `drag` flow for lasso tool activation, it will always _add_ to existing selection. I'd be fine with that.

**Review by barmac — CHANGES_REQUESTED** [review]
Let's fix what @nikku pointed out above.

**Comment by philippfromme** [comment]
> Observation: We break existing `SHIFT` + `drag` flow for lasso tool activation, it will always _add_ to existing selection. I'd be fine with that.

I've noticed that and checked how Miro does it. Works the same there.

**Comment by philippfromme** [comment]
> Nit-pick: If I start the tool without `SHIFT` I'd expect the existing selection to go away:

I'm not sure what you mean. What isn't working as expected?

**Comment by nikku** [comment]
> I'm not sure what you mean. What isn't working as expected?

The moment I start the lasso tool without `SHIFT` the old selection will vanish; hence I propose to remove it once the tool is started.

**Comment by philippfromme** [comment]
> The moment I start the lasso tool without `SHIFT` the old selection will vanish (new one will not be added to old one); hence I propose to remove it once the tool is started. Cf. attached screen capture.

So you mean you press <kbd>L</kbd> and expect the existing selection to go away?

**Comment by nikku** [comment]
Yes. Sorry if my explanation was misleading.

**Comment by philippfromme** [comment]
> Yes. Sorry if my explanation was misleading.

But that's the same as clicking the palette icon. I wouldn't expect the selection to go away immediately after just activating the tool. I would expect the selection to go away after selecting the recangular area without pressing <kbd>SHIFT</kbd>.

**Comment by nikku** [comment]
> I would expect the selection to go away after selecting the recangular area without pressing SHIFT.

I'd expect the opposite :upside_down_face:. Let's do a quick poll to resolve this, and proceed afterwards.

**Comment by philippfromme** [comment]
> I'd expect the opposite 🙃. Let's do a quick poll to resolve this, and proceed afterwards.

But that would mean you must press <kbd>SHIFT</kbd> while activating the lasso through click or <kbd>L</kbd> before even selecting anything.

**Comment by nikku** [comment]
To clarify, this is the interaction I'd expect (recorded from excalidraw):

capture J9JaEn_optimized

**Comment by philippfromme** [comment]
I had to keep `keepSelection: true;` for both `#activateLasso` and `#activateSelection`, otherwise the selection is lost even if I just want to hide it during the `selection` phase. Therefore, the only way of hiding the selection is to use CSS so I added a `djs-lasso-selection` class.

**Comment by nikku** [comment]
> I had to keep keepSelection: true; for both #activateLasso and #activateSelection, otherwise the selection is lost even if I just want to hide it during the selection phase. Therefore, the only way of hiding the selection is to use CSS so I added a djs-lasso-selection class.

Why is it lost?

**Comment by philippfromme** [comment]
> > I had to keep keepSelection: true; for both #activateLasso and #activateSelection, otherwise the selection is lost even if I just want to hide it during the selection phase. Therefore, the only way of hiding the selection is to use CSS so I added a djs-lasso-selection class.
> 
> Why is it lost?

I've checked again and it's actually restored so there's a different issue. I'll fix that. 😓

**Comment by philippfromme** [comment]
@nikku I found a different solution. Unfortunately, calling `Selection#select` with `add = true` on `lasso.end` isn't possible since the restoring of the selection that `Dragging` attempts is done only _after_ `cleanup` has already been fired so there is no way to _first_ let `Dragging` restore the selection and _then_ add elements to the selection.

**Comment by barmac** [comment]
Perhaps `Dragging` could be even more low-level. It is the selection who should handle selection and not dragging as it is in:

https://github.com/bpmn-io/diagram-js/blob/develop/lib/features/dragging/Dragging.js#L235

**Comment by barmac** [comment]
After rebase, I cannot run this with `bpmn-js` due to missing touch support module.

**Comment by barmac** [comment]
I can look into this on Monday, otherwise feel free to wrap it up.

**Comment by nikku** [comment]
@barmac Happy if you take this over :crossed_fingers:

**Comment by barmac** [comment]
Let's ship it, and we can improve on the visuals in the future. Better provide value early and we can also collect feedback on the next steps if necessary.

**Pull request merged**
